# Generated by Django 2.1.2 on 2018-11-03 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20181103_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='des',
            new_name='desc',
        ),
    ]
